import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import NextTopLoader from 'nextjs-toploader';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TeamTracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader 
        color="#95291f"
        initialPosition={0.08}
        crawlSpeed={200}
        height={3}
        crawl={true}
        showSpinner={true}
        easing="ease"
        speed={200}
        shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        template='<div class="bar" role="bar"><div class="peg"></div></div> 
        <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
        zIndex={1600}
        showAtBottom={false}
      />
         <div className='flex w-full h-screen bg-[#f9f6ee] '>
        <div className='w-1/5 h-full pt-10'>
        <Sidebar/>
        </div>
        <div className='w-full h-full p-5'>
        <div className='w-full h-full bg-[#f2edde] p-5 rounded-2xl'>
        {children}
        </div>
        </div>
    </div></body>
    </html>
  );
}
